{% set version = "2.1-6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-smacof
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/smacof_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/smacof/smacof_{{ version }}.tar.gz
  sha256: 4a1d58f6f2e8fb5582fd672dc2f6d5784a03702d8c748b972e0be1c4d6dcad1a

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-hmisc
    - r-mass
    - r-candisc
    - r-colorspace
    - r-doparallel
    - r-e1071
    - r-ellipse
    - r-foreach
    - r-nnls
    - r-plotrix
    - r-polynom
    - r-weights
    - r-wordcloud

  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-hmisc
    - r-mass
    - r-candisc
    - r-colorspace
    - r-doparallel
    - r-e1071
    - r-ellipse
    - r-foreach
    - r-nnls
    - r-plotrix
    - r-polynom
    - r-weights
    - r-wordcloud

test:
  commands:
    - $R -e "library('smacof')"           # [not win]
    - "\"%R%\" -e \"library('smacof')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=smacof
  license: GPL-3.0-only
  summary: 'Implements the following approaches for multidimensional scaling (MDS) based on stress minimization using majorization (smacof): ratio/interval/ordinal/spline MDS on symmetric dissimilarity matrices, MDS with external constraints on the configuration, individual differences scaling (idioscal, indscal), MDS with
    spherical restrictions, and ratio/interval/ordinal/spline unfolding (circular restrictions, row-conditional). Various tools and extensions like jackknife MDS, bootstrap MDS, permutation tests, MDS biplots, gravity models, unidimensional scaling, drift vectors (asymmetric MDS), classical scaling, and Procrustes are implemented
    as well.'

  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
